@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 02 10:27:44 +0300 2020
REM SW Build 2580384 on Sat Jun 29 08:12:21 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim TB_HDL_Example_4_32b_time_synth -key {Post-Synthesis:sim_1:Timing:TB_HDL_Example_4_32b} -tclbatch TB_HDL_Example_4_32b.tcl -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32a_behav.wcfg -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32b_behav.wcfg -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32a_behav1.wcfg -log simulate.log"
call xsim  TB_HDL_Example_4_32b_time_synth -key {Post-Synthesis:sim_1:Timing:TB_HDL_Example_4_32b} -tclbatch TB_HDL_Example_4_32b.tcl -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32a_behav.wcfg -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32b_behav.wcfg -view C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.32 PATTERN RECOGNIZER MEALY FSM/TB_HDL_Example_4_32a_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
