webtalk_init -webtalk_dir C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.19 RESETTABLE ENABLED REGISTER/HDL Example 4.19 RESETTABLE ENABLED REGISTER.sim/sim_1/behav/xsim/xsim.dir/TB_HDL_Example_4_19_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr  1 15:44:33 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2580384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e8602fda-d40b-4d72-a3e1-39c69e974502" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5a92e2ec8d2b4a53aaba85698f82b1b2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3174337587 -regid "" -xml C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.19 RESETTABLE ENABLED REGISTER/HDL Example 4.19 RESETTABLE ENABLED REGISTER.sim/sim_1/behav/xsim/xsim.dir/TB_HDL_Example_4_19_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.19 RESETTABLE ENABLED REGISTER/HDL Example 4.19 RESETTABLE ENABLED REGISTER.sim/sim_1/behav/xsim/xsim.dir/TB_HDL_Example_4_19_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.19 RESETTABLE ENABLED REGISTER/HDL Example 4.19 RESETTABLE ENABLED REGISTER.sim/sim_1/behav/xsim/xsim.dir/TB_HDL_Example_4_19_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
