# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a15tcpg236-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/HDL Example 4.34a PARAM N-BIT MULT.cache/wt} [current_project]
set_property parent.project_path {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/HDL Example 4.34a PARAM N-BIT MULT.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/HDL Example 4.34a PARAM N-BIT MULT.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux2/mux2.sv}
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux4_8.sv}
}
read_verilog -library xil_defaultlib {
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux2/mux2.v}
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux4_8.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux2/mux2 .vhd}
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux4_8.vhd}
  {C:/Zynq_Book/VHDL_SV_Verilog/HDL Example 4.34a PARAMETERIZED N-BIT MULTIPLEXERS/mux4_8_top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mux4_8_top -part xc7a15tcpg236-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mux4_8_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mux4_8_top_utilization_synth.rpt -pb mux4_8_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
